### ISSUE TITLE
verify with blockchain signatures

### ISSUE THREAD

**Issue by fanatid** [cryptocoinjs/secp256k1-node#70] opened 2016-02-18 04:32 UTC
I think that we should write script that checks all signatures from blockchain (testnet3 and mainnet).
https://github.com/indutny/elliptic/issues/78

**Comment by dcousens** [comment] 2016-02-18 05:12
Agreed.

The question is how strict are we?  How do we effectively soft-fork the signature checking?

**Comment by indutny** [comment] 2016-02-18 05:14
I would really suggest being as strong as possible, possibly having different validation algorithms for old signatures.

**Comment by dcousens** [comment] 2016-02-18 05:15
@indutny that is my thoughts too.

**Comment by chjj** [comment] 2016-05-10 08:44
BCoin has now validated the entire main chain and testnet chain with secp256k1-node. I had to alter historical signatures (length and high S values) in order to verify sigs in the early chain, but other than that it works well.

https://github.com/bcoin-org/bcoin/blob/master/lib/bcoin/ec.js#L110

**Comment by fanatid** [comment] 2016-05-10 09:32
@chjj OOI what version of secp256k1-node was used? I worried that with 3.1.0 importSignature became more strictly.
as I understand bitcoin-core/secp256k1 bindings was used for validating?

**Comment by chjj** [comment] 2016-05-10 09:48
@fanatid, I used the regular v3.0.0 npm package, but I will no doubt upgrade to 3.1.0. It shouldn't take long for me to test it again since I sync the blockchain quite frequently. I tend to add an optimization to bcoin's blockchain practically every other day and then sync up to at least height 130-200k to see if it improved things (I feel like I've used more of sipa's bandwidth than I deserve).

I haven't tested the blockchain sync in the browser yet.

**Comment by chjj** [comment] 2016-05-10 09:50
Oh, I almost forgot: I _did_ notice that if a zero-length key is passed to secp256k1.verify, it will go into an infinite loop and hang the process. This was never an issue when validating the blockchain, but it is a major issue when running the bitcoind unit tests for scripts and transactions (they have some weird scripts in there). The simple workaround was to just check for a zero-length buffer before passing it into verify().

**Comment by fanatid** [comment] 2016-05-10 09:54
@chjj `secp256k1.verify(message, signature, new Buffer(0))` ?

**Comment by chjj** [comment] 2016-05-10 09:56
@fanatid, yeah, that's what seemed to cause it. I never bothered to isolate it and reproduce it though. I could probably reproduce it exactly by removing the `if (key.length === 0) return false;` from my wrapper function and replicating the exact args that get passed in during the bitcoind script tests.

**Comment by axic** [comment] 2016-05-10 14:10
@fanatid can we somehow merge the `toLowS`/`isLowS` methods? It would be useful for Ethereum too (_pre-Homestead old signatures, haha_, did allow high S).

**Comment by fanatid** [comment] 2016-05-10 16:04
@axic we already have `toLowS` as method [signatureNormalize](https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md#signaturenormalizebuffer-signature---buffer)

**Comment by fanatid** [comment] 2016-05-10 16:06
isLowS can be implemented as:

``` js
function isLowS (sig) { return !secp256k1.signatureNormalize(sig).equals(sig) }
```

**Comment by axic** [comment] 2016-05-10 16:35
> @axic we already have toLowS as method signatureNormalize

Good to know, I have to use that then!

> function isLowS (sig) { return !secp256k1.signatureNormalize(sig).equals(sig) }

Is that optimal? `isLowS` shouldn't only be a matter of a single comparison?

**Comment by fanatid** [comment] 2016-05-10 16:55
> > function isLowS (sig) { return !secp256k1.signatureNormalize(sig).equals(sig) }
> 
> Is that optimal? `isLowS` shouldn't only be a matter of a single comparison?

of course this is not optimal, just easiest way to do this without extra work on secp256k1-node :)

**Comment by axic** [comment] 2016-05-10 17:09
@fanatid I know you like adding nice interfaces 😉

**Comment by dcousens** [comment] 2016-12-22 06:56
Should this be closed as of https://github.com/cryptocoinjs/secp256k1-node/issues/70#issuecomment-218106653?

**Closed as completed** 2016-12-22 07:01 UTC
